# -*- coding: utf-8 -*-
"""Assignment4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oouwLwXNIgu78U-9tM62WZxNrSNjP-90
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib notebook

plt.style.use('seaborn-colorblind')

ohio = pd.read_csv('sample_data/ohio-history.csv')
new_mexico = pd.read_csv('sample_data/new-mexico-history.csv')

ohio.info()

new_mexico.info()

ohio['ratio'] = (ohio['death'] / ohio['positive'])
ohio['ratio'].plot()

new_mexico['ratio'] = (new_mexico['death'] / new_mexico['positive'])
new_mexico['ratio'].plot()

fig = plt.figure()
plt.plot(ohio['ratio'], label='Ohio death / positive ratio', alpha=0.5)
plt.plot(new_mexico['ratio'], label='New Mexico death / positive ratio', alpha=0.5)
plt.title('Death / Positive Ratio (March 2020 - March 2021)')
plt.xlabel('Day')
plt.ylabel('Ratio')
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['top'].set_visible(False)
plt.legend()

new_df = np.concatenate((ohio['ratio'], new_mexico['ratio']))

plt.figure()
# we can pass keyword arguments for each individual component of the plot
sns.distplot(new_df, hist_kws={'color': 'Teal'}, kde_kws={'color': 'Navy'});

sns.jointplot(ohio['ratio'], new_mexico['ratio'], alpha=0.4)

